---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: misty-python-api
  name: misty-python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misty-python-api
  template:
    metadata:
      labels:
        app: misty-python-api
    spec:
      priorityClassName: p4
      containers:
      - image: docker.apple.com/2320580541/misty-python-api:202408261133
        name: misty-python-api
        ports:
        - containerPort: 5000
          name: web
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: misty-python-api
  labels:
    app: misty-python-api
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 5000
      protocol: TCP
      targetPort: web
  selector:
    app: misty-python-api
---
apiVersion: pie.apple.com/v1alpha1
kind: AppleNetworkPolicy
metadata:
  name: whitelist-snip-misty-python-api
spec:
  selector:
    app: misty-python-api
  apps_incoming:
    - app: plb.pie-plb.pie-prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yuwen-misty-backend.us-west-2d.app.apple.com
  annotations:
    kubernetes.io/ingress.class: "plb.v1"
spec:
  defaultBackend:
    service:
      name: misty-python-api
      port: 
        number: 5000
