apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: amp-data-collection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: build-robot-role
  namespace: amp-data-collection
rules:
  - apiGroups: ["extensions","apps","pie.apple.com","networking.k8s.io",""]
    resources: ["deployments","services","applenetworkpolicies","ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-robot-rolebinding
  namespace: amp-data-collection
subjects:
  - kind: ServiceAccount
    name: build-robot
    namespace: amp-data-collection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-robot-role
